//! adapters-ooa — Observation-Only Adapter (C3 §5.2 + §14.1 Phase 5
//! item #26).
//!
//! Implements `ChainAdapter` for non-integrated (hostile / unpermissioned)
//! chains. The OOA adapter is **NOT** an execution adapter — it only
//! **observes** via Channel 6 (public-blockchain direct indexing, no
//! permission required).
//!
//! Per C3 §5.2 verbatim:
//!
//! ```text
//! // ooa_anchor.rs
//! pub struct OOAConfig {
//!     pub chain_id:          ChainId,
//!     pub observation_depth: u64,           // blocks of observation history
//!     pub ooa_conf:          f64,           // current confidence (< integrated_conf)
//!     pub ooa_penalty_factor: f64,          // Θ_OOA(t) = Θ_base(t) × ooa_penalty_factor
//! }
//!
//! pub fn ooa_confidence(depth: u64, chain_tvl: f64) -> f64 {
//!     let conf_max = 0.85_f64; // approaches but does not reach integrated (1.0)
//!     let k = 0.001_f64;       // growth rate (calibrated)
//!     conf_max * (1.0 - (-k * depth as f64).exp())
//! }
//! ```
//!
//! The OOA adapter implements `ChainAdapter` for trait-object
//! dispatch homogeneity (so the router can hold `Vec<Box<dyn
//! ChainAdapter>>` covering integrated + OOA chains uniformly), but
//! every `execute_*` method returns [`TxHash::zero()`] (the canonical
//! "no transaction broadcast" sentinel — observation-only chains do
//! not execute) and [`ChainAdapter::verify_execution`] returns
//! [`ExecutionResult::NotImplemented`].
//!
//! The OOA-specific observation surface lives in the extra methods
//! [`OoaAdapter::observe_chain`] and [`OoaAdapter::compute_ooa_confidence`].

use adapters_core::{
    ChainAdapter, ChainId, ExecutionResult, Intent, Route, TxHash,
};
use serde::{Deserialize, Serialize};

/// C3 §5.2 OOA confidence asymptote. Approaches but does not reach
/// integrated confidence (1.0).
const OOA_CONF_MAX: f64 = 0.85;

/// C3 §5.2 OOA growth rate (calibrated). `k = 0.001` per the spec.
const OOA_K: f64 = 0.001;

/// OOA confidence computation per C3 §5.2 verbatim:
///
/// ```text
/// OOA_conf(depth) = conf_max × (1 - e^(-k × depth))
/// ```
///
/// At `depth = 0` returns 0 (no observation yet). Grows monotonically
/// and asymptotically toward `conf_max = 0.85` as `depth → ∞`. At
/// ~12 months of observation + sufficient cross-chain shadow evidence,
/// OOA effectively approaches integrated performance.
///
/// The `tvl` parameter is part of the spec signature for future
/// calibration (currently unused — the spec only references `depth`).
pub fn compute_ooa_confidence(depth: u64, tvl: f64) -> f64 {
    let _ = tvl; // reserved for future TVL-weighted calibration
    OOA_CONF_MAX * (1.0 - (-OOA_K * depth as f64).exp())
}

/// OOA configuration (C3 §5.2 `OOAConfig`).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OOAConfig {
    /// Canonical chain id of the observed (non-integrated) chain.
    pub chain_id: ChainId,
    /// Blocks of observation history accumulated so far.
    pub observation_depth: u64,
    /// Current confidence in the chain's behavioral observations.
    pub ooa_conf: f64,
    /// Θ_OOA(t) = Θ_base(t) × ooa_penalty_factor — OOA chains score
    /// lower in BTCP_score routing.
    pub ooa_penalty_factor: f64,
}

impl Default for OOAConfig {
    fn default() -> Self {
        OOAConfig {
            chain_id: 0,
            observation_depth: 0,
            ooa_conf: 0.0,
            ooa_penalty_factor: 1.0,
        }
    }
}

/// Behavioral event observed on a non-integrated chain. The OOA adapter
/// emits these in lieu of execution receipts — Channel 6 reads public
/// chain state directly and produces [`BehavioralEvent`] records for
/// downstream ingestion by the Akashic Index / FAISS.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BehavioralEvent {
    /// Canonical chain id of the observed chain.
    pub chain_id: ChainId,
    /// Block height at which the event was observed.
    pub block_number: u64,
    /// Event class tag — matches the 20-code EventType from
    /// `trion-common::hash_dna::classify_event_type` (TRANSFER=0 …
    /// CLAIM=19).
    pub event_type: u8,
    /// SHA-256 / Keccak hash of the event payload (the behavioral
    /// fingerprint).
    pub event_hash: [u8; 32],
    /// Observation depth at the time of this event (monotonically
    /// increasing — used by `compute_ooa_confidence` for confidence
    /// growth calibration).
    pub observation_depth: u64,
    /// `true` when this event was generated by a SYNTHETIC-DEMO
    /// observation pass rather than read from a real Channel 6 indexer
    /// feed. Downstream consumers MUST check this flag before treating
    /// the event as a real observation (R-LABELS).
    pub simulated: bool,
}

/// Observation-Only Adapter (C3 §5.2). Does NOT execute — only
/// observes.
#[derive(Debug, Clone)]
pub struct OoaAdapter {
    config: OOAConfig,
}

impl OoaAdapter {
    /// Construct an OOA adapter with the given chain id and an initial
    /// observation depth of 0.
    pub fn new(chain_id: ChainId) -> Self {
        let mut config = OOAConfig::default();
        config.chain_id = chain_id;
        OoaAdapter { config }
    }

    /// Construct an OOA adapter with an explicit configuration.
    pub fn with_config(config: OOAConfig) -> Self {
        OoaAdapter { config }
    }

    /// Borrow the OOA configuration.
    pub fn config(&self) -> &OOAConfig {
        &self.config
    }

    /// Observe `depth` blocks of chain history via Channel 6
    /// (no-permission indexing per C3 §5.2). Returns the
    /// [`BehavioralEvent`]s collected during the observation window.
    ///
    /// R-LABELS: in this SYNTHETIC-DEMO stand-in the events are derived
    /// deterministically from `(chain_id, depth)` — the `simulated`
    /// flag is set on every emitted event so downstream consumers can
    /// never mistake these for real Channel 6 indexer data.
    pub fn observe_chain(&self, chain_id: ChainId, depth: u64) -> Vec<BehavioralEvent> {
        // SYNTHETIC-DEMO: synthesize one event per observation block.
        // Real Channel 6 wiring must replace this with the trion-evm /
        // trion-svm / trion-cosmos / etc. indexer RPC reading per
        // C3 §14.1 Phase 1 ("Channel 6 observation — extend existing
        // evm_adapter RPC reading").
        let effective_chain_id = if chain_id == 0 {
            self.config.chain_id
        } else {
            chain_id
        };
        let mut events = Vec::new();
        for i in 0..depth {
            let block_number = self.config.observation_depth + i + 1;
            // Event class cycles through the 20 canonical codes per
            // trion-common::classify_event_type. For the SYNTHETIC-DEMO
            // path, alternate between TRANSFER (0) and SWAP (1) so the
            // downstream Akashic Index sees a representative mix.
            let event_type = ((i % 2) as u8) * 1; // 0 or 1
            let payload = format!(
                "OOA-SYNTHETIC-DEMO|chain={}|block={}|event={}|seq={}",
                effective_chain_id, block_number, event_type, i
            );
            let hash = adapters_core::synthetic_tx_hash(payload.as_bytes());
            events.push(BehavioralEvent {
                chain_id: effective_chain_id,
                block_number,
                event_type,
                event_hash: hash.0,
                observation_depth: block_number,
                simulated: true,
            });
        }
        events
    }

    /// Compute the OOA confidence for `depth` blocks of observation on
    /// a chain with `tvl` USD-equivalent TVL (C3 §5.2 verbatim). Delegates
    /// to [`compute_ooa_confidence`].
    pub fn compute_ooa_confidence(&self, depth: u64, tvl: f64) -> f64 {
        compute_ooa_confidence(depth, tvl)
    }

    /// Update the adapter's accumulated observation depth (mutates
    /// internal state).
    pub fn advance_depth(&mut self, additional_blocks: u64) {
        self.config.observation_depth =
            self.config.observation_depth.saturating_add(additional_blocks);
        // Recompute ooa_conf for the new depth (no TVL signal in this
        // SYNTHETIC-DEMO stand-in; pass 0.0).
        self.config.ooa_conf = compute_ooa_confidence(self.config.observation_depth, 0.0);
    }
}

/// The OOA adapter implements `ChainAdapter` for trait-object dispatch
/// homogeneity (so the router can hold `Vec<Box<dyn ChainAdapter>>`
/// covering integrated + OOA chains uniformly), but every `execute_*`
/// method returns [`TxHash::zero()`] (no transaction broadcast —
/// observation-only chains do not execute) and
/// [`ChainAdapter::verify_execution`] returns
/// [`ExecutionResult::NotImplemented`].
impl ChainAdapter for OoaAdapter {
    fn chain_id(&self) -> ChainId {
        self.config.chain_id
    }

    fn vm_type(&self) -> &'static str {
        "OOA"
    }

    /// OOA does not execute — returns the fail-closed `TxHash::zero()`
    /// sentinel. The router MUST NOT route execution intents through an
    /// OOA adapter (OOA chains are observation-only).
    fn execute_swap(&self, _intent: &Intent, _route: &Route) -> TxHash {
        TxHash::zero()
    }

    /// OOA does not execute.
    fn execute_transfer(&self, _intent: &Intent, _route: &Route) -> TxHash {
        TxHash::zero()
    }

    /// OOA does not execute.
    fn execute_liquidity(&self, _intent: &Intent, _route: &Route) -> TxHash {
        TxHash::zero()
    }

    /// OOA does not execute.
    fn execute_borrow(&self, _intent: &Intent, _route: &Route) -> TxHash {
        TxHash::zero()
    }

    /// OOA does not execute.
    fn execute_stake(&self, _intent: &Intent, _route: &Route) -> TxHash {
        TxHash::zero()
    }

    /// Verify is NotImplemented for OOA chains (no execution to verify).
    fn verify_execution(&self, _tx_hash: TxHash) -> ExecutionResult {
        ExecutionResult::NotImplemented
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use adapters_core::IntentAction;

    /// C3 §5.2 formula sanity: at depth = 0, OOA_conf = 0.
    #[test]
    fn test_ooa_confidence_at_depth_zero() {
        let conf = compute_ooa_confidence(0, 1_000_000_000.0);
        assert!(
            conf.abs() < 1e-9,
            "depth=0 → ooa_conf=0, got {}",
            conf
        );
    }

    /// C3 §5.2 formula sanity: at large depth, OOA_conf approaches
    /// conf_max = 0.85 (but does not reach it in finite f64 precision
    /// — at depth = 5000 blocks OOA_conf ≈ 0.844, strictly < 0.85).
    #[test]
    fn test_ooa_confidence_asymptotic_to_conf_max() {
        // At depth = 5_000 blocks, OOA_conf = 0.85 × (1 - e^(-5))
        //                       ≈ 0.85 × 0.99326 ≈ 0.8443.
        // At depth = 100_000 blocks, the formula mathematically equals
        // 0.85 × (1 - e^(-100)) which rounds to exactly 0.85 in f64
        // precision — the asymptote is reached, not crossed.
        let conf = compute_ooa_confidence(5_000, 1_000_000_000.0);
        assert!(conf > 0.84, "should be near conf_max: got {}", conf);
        assert!(conf < 0.85, "should be strictly less than conf_max: got {}", conf);
    }

    /// C3 §5.2 formula: OOA_conf is monotonically non-decreasing in
    /// depth.
    #[test]
    fn test_ooa_confidence_monotonic_in_depth() {
        let mut prev = 0.0_f64;
        for depth in [1u64, 10, 100, 1_000, 10_000, 100_000] {
            let conf = compute_ooa_confidence(depth, 1_000_000.0);
            assert!(
                conf >= prev,
                "non-monotonic at depth {}: prev={} cur={}",
                depth,
                prev,
                conf
            );
            prev = conf;
        }
    }

    /// OOA adapter exposes `compute_ooa_confidence` as an instance
    /// method too.
    #[test]
    fn test_adapter_compute_ooa_confidence() {
        let adapter = OoaAdapter::new(999);
        let c1 = adapter.compute_ooa_confidence(100, 1_000_000.0);
        let c2 = compute_ooa_confidence(100, 1_000_000.0);
        assert!((c1 - c2).abs() < 1e-9, "instance and free fn agree");
    }

    /// `observe_chain` returns the expected number of events and tags
    /// each as `simulated: true` (R-LABELS — SYNTHETIC-DEMO stand-in).
    #[test]
    fn test_observe_chain_emits_simulated_events() {
        let adapter = OoaAdapter::new(42);
        let depth = 10u64;
        let events = adapter.observe_chain(42, depth);
        assert_eq!(events.len() as u64, depth);
        for event in &events {
            assert_eq!(event.chain_id, 42);
            assert!(event.simulated, "every event carries the SYNTHETIC-DEMO flag");
            assert!(event.event_hash != [0u8; 32], "event_hash is non-zero");
        }
    }

    /// `observe_chain(0, depth)` falls back to the adapter's configured
    /// chain_id (chain_id = 0 sentinel → use self.config.chain_id).
    #[test]
    fn test_observe_chain_zero_chain_id_falls_back() {
        let adapter = OoaAdapter::new(777);
        let events = adapter.observe_chain(0, 3);
        assert_eq!(events.len(), 3);
        for event in &events {
            assert_eq!(event.chain_id, 777);
        }
    }

    /// Observation depth grows monotonically across multiple observe
    /// calls — each call's `observation_depth` field strictly increases.
    #[test]
    fn test_observe_chain_depth_grows_monotonically() {
        let adapter = OoaAdapter::new(42);
        let events = adapter.observe_chain(42, 5);
        // First event at block_number = observation_depth+1 = 1, second at 2, etc.
        for (i, event) in events.iter().enumerate() {
            assert_eq!(event.block_number, (i + 1) as u64);
        }
    }

    /// `advance_depth` mutates the adapter's accumulated depth and
    /// recomputes `ooa_conf`.
    #[test]
    fn test_advance_depth_recomputes_ooa_conf() {
        let mut adapter = OoaAdapter::new(42);
        assert_eq!(adapter.config().observation_depth, 0);
        assert!(adapter.config().ooa_conf.abs() < 1e-9);
        adapter.advance_depth(1000);
        assert_eq!(adapter.config().observation_depth, 1000);
        let expected = compute_ooa_confidence(1000, 0.0);
        assert!((adapter.config().ooa_conf - expected).abs() < 1e-9);
    }

    /// ChainAdapter trait object dispatch — every execute_* returns
    /// `TxHash::zero()` (no execution for OOA chains) and
    /// `verify_execution` returns `NotImplemented`.
    #[test]
    fn test_trait_object_dispatch_is_no_op() {
        let adapter: Box<dyn ChainAdapter> = Box::new(OoaAdapter::new(42));
        assert_eq!(adapter.chain_id(), 42);
        assert_eq!(adapter.vm_type(), "OOA");

        let intent = Intent {
            action: IntentAction::Swap,
            source_chain: 42,
            dest_chain: 42,
            asset_in: String::from("foo"),
            asset_out: String::from("bar"),
            amount_in: 1_000,
            source_address: String::from("source"),
            dest_address: String::from("dest"),
            min_amount_out: None,
            deadline: 0,
        };
        let route = Route {
            route_id: TxHash::zero(),
            intent: intent.clone(),
            exec_chain: None,
        };

        // R-FAILCLOSED-style discipline: OOA never executes; every
        // execute_* returns the zero-hash sentinel.
        assert!(adapter.execute_swap(&intent, &route).is_zero());
        assert!(adapter.execute_transfer(&intent, &route).is_zero());
        assert!(adapter.execute_liquidity(&intent, &route).is_zero());
        assert!(adapter.execute_borrow(&intent, &route).is_zero());
        assert!(adapter.execute_stake(&intent, &route).is_zero());

        // verify_execution returns NotImplemented (distinct from
        // Failed — the OOA chain did not even attempt execution).
        assert!(matches!(
            adapter.verify_execution(TxHash::zero()),
            ExecutionResult::NotImplemented
        ));
        assert!(matches!(
            adapter.verify_execution(adapters_core::synthetic_tx_hash(b"any-non-zero")),
            ExecutionResult::NotImplemented
        ));
    }

    /// OOAConfig Default produces a zero-config chain.
    #[test]
    fn test_ooa_config_default() {
        let cfg = OOAConfig::default();
        assert_eq!(cfg.chain_id, 0);
        assert_eq!(cfg.observation_depth, 0);
        assert!(cfg.ooa_conf.abs() < 1e-9);
        assert!((cfg.ooa_penalty_factor - 1.0).abs() < 1e-9);
    }

    /// OOA with explicit config via `with_config`.
    #[test]
    fn test_with_config() {
        let cfg = OOAConfig {
            chain_id: 100,
            observation_depth: 5_000,
            ooa_conf: 0.5,
            ooa_penalty_factor: 0.8,
        };
        let adapter = OoaAdapter::with_config(cfg);
        assert_eq!(adapter.chain_id(), 100);
        assert_eq!(adapter.config().observation_depth, 5_000);
    }
}
