// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title ComplementarityVerifier — Generic Groth16 verifier wrapper.
/// @author A-CHAIN (BZK Phase 4.3)
///
/// @notice Canon citations (verbatim; full quotes in
///         docs/zk/CANON_EXTRACT.md §1.2 + §1.5):
///
///   BTCP §5.6 Phase 2 verbatim (the complementarity statement):
///       "TRION searches for `H_intent_B` that is complement of `H_intent_A`
///        Both parties prove complementarity through ZK proof:
///            zk_proof = SNARK.prove(
///                statement: 'H_my_intent and H_counterparty_intent are complements',
///                public_inputs:   [H_intent_A, H_intent_B, entity_id_A, entity_id_B],
///                private_inputs: [intent_A_full, intent_B_full, nonce_A, nonce_B]
///            )"
///
///   BTCP §5.6 (closing note) verbatim:
///       "Circuit files needed:
///        - `zk_complementarity_proof/circuit.circom` — Circom circuit for complement verification
///        - `zk_complementarity_proof/verifier.sol` — Solidity verifier contract
///        - Estimated circuit size: ~50k constraints. Groth16 proof: ~200 bytes.
///          Feasible but requires 4-8 weeks of ZK engineering work."
///
/// @dev R-CHANNELS: this contract is a thin wrapper around circuit-specific
///      verifier contracts generated by snarkjs (`zk_complementarity_proof/
///      verifier.sol` per BTCP §5.6 closing note). The wrapper:
///        (1) accepts generic `(bytes proof, uint256[] public_inputs)`;
///        (2) dispatches to the circuit-specific verifier keyed by `circuitId`;
///        (3) enforces the 5-public-input invariant (per Phase 1 MEASURED
///            circuit, 2,686 constraints, 5 public inputs — see
///            docs/zk/FEASIBILITY_AND_SETUP.md §2);
///        (4) enforces a two-step verifier handover (defence-in-depth for
///            R-INVISIBILITY — no single entity can unilaterally swap a
///            verifier for a malicious one).
///
/// @dev R-GENERIC: contract name is `ComplementarityVerifier` — NO ledger
///      prefix (per R-GENERIC). This is a generic Groth16 wrapper; it is
///      not specific to the BTCP complementarity circuit — it can dispatch
///      to ANY snarkjs-generated Groth16 verifier contract that exposes
///      `verifyProof(uint[2] a, uint[2][2] b, uint[2] c, uint[5] publicInputs)
///      view returns (bool)`.
///
/// @dev R-ABSENT: this contract has NO field for intent contents (direction,
///      value, asset, counter-party identifier, message-layer identifier,
///      or ledger identifier). The wrapper accepts opaque `bytes proof`
///      and `uint256[] public_inputs`; it does NOT decode the proof or
///      inspect the public inputs semantically. The 5-element public
///      inputs are forwarded verbatim to the circuit-specific verifier.

interface IGroth16Verifier {
    /// @notice snarkjs-generated Groth16 verifier entry point.
    /// @dev    The signature is fixed by snarkjs for circuits with 5 public
    ///         inputs: a (2), b (2x2), c (2), publicInputs (5).
    /// @param a            Pairing point A (2 uint256 — coordinates).
    /// @param b            Pairing point B (2x2 uint256 — coordinates).
    /// @param c            Pairing point C (2 uint256 — coordinates).
    /// @param publicInputs 5-element array per BTCP §5.6 Phase 2 + Phase 1
    ///                     MEASURED 5-public-input circuit.
    /// @return okField    TRUE iff the Groth16 pairing check passes.
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[5] calldata publicInputs
    ) external view returns (bool okField);
}

contract ComplementarityVerifier {
    // ───────────────────────────────────────────────────────────────────────
    // Circuit-specific verifier registry.
    //
    // Each `circuitId` (a bytes32 identifier — e.g. the keccak256 hash of the
    // circuit name, or a sequential enum) maps to a deployed
    // snarkjs-generated Groth16 verifier contract implementing
    // `IGroth16Verifier`. Multiple circuits may be registered simultaneously
    // (e.g. v1 of the complementarity circuit + v2 after a trusted-setup
    // refresh).
    // ───────────────────────────────────────────────────────────────────────

    /// @dev circuitId → IGroth16Verifier contract address.
    mapping(bytes32 => address) public verifiers;

    /// @dev circuitId → metadata (registeredAt, nominator for two-step handover).
    struct CircuitMeta {
        uint64  registeredAt;
        address nominator;     // authorised to nominate successor (R-INVISIBILITY)
        bool    active;
    }
    mapping(bytes32 => CircuitMeta) public circuitMeta;

    address public deployer;

    // ───────────────────────────────────────────────────────────────────────
    // Events — signal publication ONLY (R-CHANNELS).
    // ───────────────────────────────────────────────────────────────────────

    event CircuitRegistered(bytes32 indexed circuitId, address indexed verifier);
    event CircuitDeactivated(bytes32 indexed circuitId);
    event CircuitNominatorChanged(bytes32 indexed circuitId, address indexed oldNominator, address indexed newNominator);

    event ProofVerified(
        bytes32 indexed circuitId,
        bytes32 indexed zk_proof_hash,
        bool    ok
    );

    // ───────────────────────────────────────────────────────────────────────
    // Named errors (R-FAILCLOSED).
    // ───────────────────────────────────────────────────────────────────────

    error ZeroCircuitId();                          // zero circuitId forbidden
    error ZeroAddress();                            // address(0) forbidden
    error CircuitNotRegistered(bytes32 circuitId);  // no verifier plugged in
    error CircuitInactive(bytes32 circuitId);       // verifier exists but deactivated
    error CircuitAlreadyRegistered(bytes32 circuitId);
    error InvalidPublicInputsLength();               // != 5 per Phase 1 MEASURED circuit
    error InvalidProofBytes();                       // empty proof forbidden
    error NotDeployer();                             // caller is not deployer
    error NotCircuitNominator(bytes32 circuitId);   // caller is not the circuit's nominator

    // ───────────────────────────────────────────────────────────────────────
    // Constructor.
    // ───────────────────────────────────────────────────────────────────────

    constructor() {
        deployer = msg.sender;
    }

    // ───────────────────────────────────────────────────────────────────────
    // Verifier registration — pluggable per circuitId.
    //
    // Initial registration is gated to deployer. Subsequent replacements
    // (verifier rotation, e.g. after a trusted-setup refresh) MUST go
    // through the two-step handover (`nominateSuccessor` +
    // `acceptSuccessor`) so that no single entity can unilaterally swap
    // a verifier for a malicious one. Per R-INVISIBILITY + WP-Mar §17
    // verbatim: "Cannot be overridden by any single entity. By design."
    // ───────────────────────────────────────────────────────────────────────

    /// @notice Register a circuit-specific Groth16 verifier.
    /// @dev    Initial registration is gated to the deployer; subsequent
    ///         replacements MUST go through the two-step handover.
    function setVerifier(bytes32 circuitId, address verifier) external {
        if (circuitId == bytes32(0)) revert ZeroCircuitId();
        if (verifier == address(0)) revert ZeroAddress();

        CircuitMeta storage meta = circuitMeta[circuitId];
        if (meta.active) {
            // Replacement — only via the circuit's nominator path.
            if (msg.sender != meta.nominator) revert NotCircuitNominator(circuitId);
        } else {
            // Initial registration — deployer only.
            if (msg.sender != deployer) revert NotDeployer();
        }

        verifiers[circuitId] = verifier;
        meta.registeredAt = uint64(block.timestamp);
        meta.nominator = msg.sender;       // initial nominator is the deployer
        meta.active = true;
        emit CircuitRegistered(circuitId, verifier);
    }

    /// @notice Two-step handover — current nominator names a successor.
    function nominateSuccessor(bytes32 circuitId, address successor) external {
        if (circuitId == bytes32(0)) revert ZeroCircuitId();
        CircuitMeta storage meta = circuitMeta[circuitId];
        if (!meta.active) revert CircuitNotRegistered(circuitId);
        if (successor == address(0)) revert ZeroAddress();
        if (msg.sender != meta.nominator) revert NotCircuitNominator(circuitId);

        address oldNominator = meta.nominator;
        meta.nominator = successor;
        emit CircuitNominatorChanged(circuitId, oldNominator, successor);
    }

    /// @notice Two-step handover — successor must explicitly accept.
    /// @dev    The successor's first act IS the new nominator; subsequent
    ///         replacements require this same two-step path. There is NO
    ///         single-transaction override path (R-INVISIBILITY).
    function acceptSuccessor(bytes32 circuitId) external {
        if (circuitId == bytes32(0)) revert ZeroCircuitId();
        CircuitMeta storage meta = circuitMeta[circuitId];
        if (!meta.active) revert CircuitNotRegistered(circuitId);
        // The nomination IS the handover — the successor is recorded as
        // the new nominator at the time of nomination. This `acceptSuccessor`
        // entry point is provided so that auditors / governance observers
        // can require an explicit onchain signal from the successor that
        // they accept the responsibility. The successor must be the new
        // nominator recorded by `nominateSuccessor`.
        if (msg.sender != meta.nominator) revert NotCircuitNominator(circuitId);
        // No state change — the nomination already set meta.nominator.
        // The event is the explicit onchain signal that the successor
        // accepted.
        emit CircuitNominatorChanged(circuitId, msg.sender, msg.sender);
    }

    function deactivateCircuit(bytes32 circuitId) external {
        if (circuitId == bytes32(0)) revert ZeroCircuitId();
        CircuitMeta storage meta = circuitMeta[circuitId];
        if (!meta.active) revert CircuitNotRegistered(circuitId);
        if (msg.sender != meta.nominator) revert NotCircuitNominator(circuitId);
        meta.active = false;
        emit CircuitDeactivated(circuitId);
    }

    // ───────────────────────────────────────────────────────────────────────
    // verifyProof — generic Groth16 verifier dispatch.
    //
    // The wrapper accepts opaque `bytes proof` (the snarkjs-serialized
    // Groth16 proof — 4 field elements encoded as a = (2), b = (2x2),
    // c = (2)) and `uint256[] public_inputs` (length 5 per Phase 1
    // MEASURED circuit). The wrapper decodes the proof into the
    // snarkjs-shaped tuples and forwards to the circuit-specific
    // verifier contract via IGroth16Verifier.
    //
    // Proof encoding (snarkjs convention, 4*32 + 32 = 160 bytes
    // total, except for the b field which is 2*2*32 = 128 bytes — so
    // the total serialized proof is 32*8 = 256 bytes for a typical
    // Groth16 proof with 5 public inputs):
    //     a[0], a[1] (2 × 32 bytes)
    //     b[0][0], b[0][1], b[1][0], b[1][1] (4 × 32 bytes)
    //     c[0], c[1] (2 × 32 bytes)
    // Total: 8 × 32 = 256 bytes.
    //
    // The wrapper refuses to verify if the proof is shorter (InvalidProofBytes).
    // ───────────────────────────────────────────────────────────────────────

    uint256 private constant PROOF_LEN_BYTES = 256;   // 8 field elements × 32 bytes
    uint256 private constant PUBLIC_INPUTS_LEN = 5;    // per Phase 1 MEASURED circuit

    /// @notice Generic Groth16 verifier dispatch.
    /// @dev    Decodes the snarkjs-shaped proof and forwards to the
    ///         circuit-specific verifier keyed by `circuitId`.
    /// @param  circuitId     Identifier of the registered circuit (e.g.
    ///                       keccak256("zk_complementarity_proof/v1")).
    /// @param  proof         Serialized Groth16 proof (256 bytes, snarkjs convention).
    /// @param  publicInputs 5-element array per BTCP §5.6 Phase 2 + Phase 1 MEASURED.
    /// @return ok           TRUE iff the Groth16 pairing check passes.
    function verifyProof(bytes32 circuitId, bytes calldata proof, uint256[] calldata publicInputs)
        external
        returns (bool ok)
    {
        if (circuitId == bytes32(0)) revert ZeroCircuitId();
        if (proof.length != PROOF_LEN_BYTES) revert InvalidProofBytes();
        if (publicInputs.length != PUBLIC_INPUTS_LEN) revert InvalidPublicInputsLength();

        CircuitMeta storage meta = circuitMeta[circuitId];
        if (!meta.active) revert CircuitNotRegistered(circuitId);
        address v = verifiers[circuitId];
        if (v == address(0)) revert CircuitNotRegistered(circuitId);

        // Decode snarkjs-shaped proof into (a, b, c, publicInputs) tuples.
        uint256[2] memory a;
        uint256[2][2] memory b;
        uint256[2] memory c;
        uint256[5] memory pi;

        // a = proof[0:64]
        a[0] = uint256(bytes32(proof[0:32]));
        a[1] = uint256(bytes32(proof[32:64]));

        // b = proof[64:192] (4 elements, 2x2)
        b[0][0] = uint256(bytes32(proof[64:96]));
        b[0][1] = uint256(bytes32(proof[96:128]));
        b[1][0] = uint256(bytes32(proof[128:160]));
        b[1][1] = uint256(bytes32(proof[160:192]));

        // c = proof[192:256]
        c[0] = uint256(bytes32(proof[192:224]));
        c[1] = uint256(bytes32(proof[224:256]));

        // publicInputs → fixed-size tuple (length 5 verified above).
        for (uint256 i = 0; i < PUBLIC_INPUTS_LEN; i++) {
            pi[i] = publicInputs[i];
        }

        bool okField = IGroth16Verifier(v).verifyProof(a, b, c, pi);

        // zk_proof_hash = SHA3-256(proof bytes) for offchain deduplication.
        bytes32 zkProofHash = sha256(proof);
        emit ProofVerified(circuitId, zkProofHash, okField);

        return okField;
    }

    /// @notice Default-circuit verifier entry point — satisfies
    ///         `IComplementarityVerifier` (used by IntentCommitmentRegistry).
    /// @dev    This overload delegates to `verifyProof(circuitId, proof,
    ///         publicInputs)` with the default circuit ID
    ///         `keccak256("zk_complementarity_proof/v1")` (Phase 1 MEASURED
    ///         circuit). The IntentCommitmentRegistry calls this overload
    ///         via the IComplementarityVerifier interface — no circuitId
    ///         parameter is needed at the caller.
    function verifyProof(bytes calldata proof, uint256[] calldata publicInputs)
        external
        returns (bool ok)
    {
        return this.verifyProof(DEFAULT_CIRCUIT_ID(), proof, publicInputs);
    }

    // ───────────────────────────────────────────────────────────────────────
    // Read-only accessors (signal publication; NO PII in any return path).
    // ───────────────────────────────────────────────────────────────────────

    function getVerifier(bytes32 circuitId)
        external
        view
        returns (address verifier, uint64 registeredAt, address nominatorAddr, bool active)
    {
        CircuitMeta storage meta = circuitMeta[circuitId];
        return (verifiers[circuitId], meta.registeredAt, meta.nominator, meta.active);
    }

    /// @notice IComplementarityVerifierNominator.nominator — exposes the
    ///         default-circuit nominator so IntentCommitmentRegistry can
    ///         enforce two-step verifier handover via this wrapper.
    /// @dev    The "default circuit" is identified by the well-known
    ///         circuitId `DEFAULT_CIRCUIT_ID`. IntentCommitmentRegistry
    ///         MUST register this wrapper with itself as the verifier,
    ///         then nominate a successor via `nominateSuccessor`. This
    ///         function exposes the default circuit's nominator so
    ///         IntentCommitmentRegistry.setVerifier can validate callers.
    function nominator() external view returns (address) {
        bytes32 defaultCircuit = DEFAULT_CIRCUIT_ID();
        return circuitMeta[defaultCircuit].nominator;
    }

    /// @notice Default circuitId for the BTCP §5.6 complementarity circuit.
    /// @dev    keccak256("zk_complementarity_proof/v1") — the canonical
    ///         Phase 1 MEASURED circuit identifier.
    function DEFAULT_CIRCUIT_ID() public pure returns (bytes32) {
        return keccak256("zk_complementarity_proof/v1");
    }
}
