#![no_std]
use soroban_sdk::{contract, contracterror, contractimpl, contracttype, Env, Address, Map, Symbol, BytesN};
#[contracttype] #[derive(Clone, Debug, PartialEq)]
pub struct Escrow { pub route_id: BytesN<32>, pub destination: Address, pub amount: u128, pub min_coherence: u64, pub lock_ledger: u32, pub timeout: u32, pub state: u32, pub locked_by: Address }
#[contracttype] #[derive(Clone, Debug, PartialEq)]
pub struct Attestation { pub coherence: u64, pub execution_bh: BytesN<32>, pub count: u32, pub last_time: u64, pub disputed: bool }
#[contracterror] #[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum Error { NotHolding=100, AlreadyReleased=101, QuorumNotReached=102, Disputed=103, CoherenceMismatch=104, StaleAttestation=105, NotValidator=106, AlreadyAttested=107, NotOwner=108, BadInput=109 }
const KEY_ESC: Symbol = Symbol::short("esc"); const KEY_ATT: Symbol = Symbol::short("att"); const KEY_ATD: Symbol = Symbol::short("atd"); const KEY_VALS: Symbol = Symbol::short("vals"); const KEY_VCNT: Symbol = Symbol::short("vcnt"); const KEY_QRM: Symbol = Symbol::short("qrm"); const KEY_OWNER: Symbol = Symbol::short("owner");
#[contract] pub struct BTCPEscrow;
#[contractimpl]
impl BTCPEscrow {
    pub fn init(env: Env, owner: Address) { env.storage().instance().set(&KEY_OWNER, &owner); env.storage().instance().set(&KEY_QRM, &3u32); env.storage().instance().set(&KEY_VCNT, &0u32); }
    pub fn add_validator(env: Env, invoker: Address, v: Address) -> Result<bool, Error> { invoker.require_auth(); let owner: Address = env.storage().instance().get(&KEY_OWNER).unwrap(); if invoker != owner { return Err(Error::NotOwner); } let mut vals: Map<Address, bool> = env.storage().instance().get(&KEY_VALS).unwrap_or_else(|| Map::new(&env)); if vals.contains_key(v.clone()) { return Err(Error::AlreadyAttested); } vals.set(v, true); env.storage().instance().set(&KEY_VALS, &vals); let c: u32 = env.storage().instance().get(&KEY_VCNT).unwrap_or(0); env.storage().instance().set(&KEY_VCNT, &(c + 1)); Ok(true) }
    pub fn set_quorum(env: Env, invoker: Address, q: u32) -> Result<bool, Error> { invoker.require_auth(); let owner: Address = env.storage().instance().get(&KEY_OWNER).unwrap(); if invoker != owner { return Err(Error::NotOwner); } if q == 0 { return Err(Error::BadInput); } env.storage().instance().set(&KEY_QRM, &q); Ok(true) }
    pub fn lock_escrow(env: Env, escrow_id: BytesN<32>, route_id: BytesN<32>, destination: Address, amount: u128, min_coherence: u64, timeout: u32) -> Result<bool, Error> { if amount == 0 { return Err(Error::BadInput); } let mut escrows: Map<BytesN<32>, Escrow> = env.storage().persistent().get(&KEY_ESC).unwrap_or_else(|| Map::new(&env)); if escrows.contains_key(escrow_id.clone()) { return Err(Error::AlreadyReleased); } escrows.set(escrow_id, Escrow { route_id, destination, amount, min_coherence, lock_ledger: env.ledger().sequence(), timeout, state: 0, locked_by: env.current_contract_address() }); env.storage().persistent().set(&KEY_ESC, &escrows); Ok(true) }
    pub fn submit_attestation(env: Env, invoker: Address, route_id: BytesN<32>, coherence: u64, execution_bh: BytesN<32>, attestation_time: u64) -> Result<bool, Error> { invoker.require_auth(); let vals: Map<Address, bool> = env.storage().instance().get(&KEY_VALS).unwrap_or_else(|| Map::new(&env)); if !vals.get(invoker.clone()).unwrap_or(false) { return Err(Error::NotValidator); } let mut atd: Map<BytesN<32>, bool> = env.storage().persistent().get(&KEY_ATD).unwrap_or_else(|| Map::new(&env)); if atd.contains_key(route_id.clone()) { return Err(Error::AlreadyAttested); } atd.set(route_id.clone(), true); env.storage().persistent().set(&KEY_ATD, &atd); let mut atts: Map<BytesN<32>, Attestation> = env.storage().persistent().get(&KEY_ATT).unwrap_or_else(|| Map::new(&env)); let existing = atts.get(route_id.clone()); match existing { None => { atts.set(route_id, Attestation { coherence, execution_bh, count: 1, last_time: attestation_time, disputed: false }); } Some(att) => { if att.disputed { return Err(Error::Disputed); } if coherence == att.coherence && execution_bh == att.execution_bh { atts.set(route_id, Attestation { coherence, execution_bh, count: att.count + 1, last_time: attestation_time, disputed: false }); } else { atts.set(route_id, Attestation { coherence: att.coherence, execution_bh: att.execution_bh, count: att.count, last_time: attestation_time, disputed: true }); } } } env.storage().persistent().set(&KEY_ATT, &atts); Ok(true) }
    pub fn release_escrow(env: Env, escrow_id: BytesN<32>, execution_bh: BytesN<32>, coherence: u64, current_time: u64) -> Result<bool, Error> { let mut escrows: Map<BytesN<32>, Escrow> = env.storage().persistent().get(&KEY_ESC).unwrap_or_else(|| Map::new(&env)); let mut escrow = match escrows.get(escrow_id.clone()) { Some(e) => e, None => return Err(Error::NotHolding) }; if escrow.state != 0 { return Err(Error::AlreadyReleased); } let atts: Map<BytesN<32>, Attestation> = env.storage().persistent().get(&KEY_ATT).unwrap_or_else(|| Map::new(&env)); let att = match atts.get(escrow.route_id.clone()) { Some(a) => a, None => return Err(Error::QuorumNotReached) }; let q: u32 = env.storage().instance().get(&KEY_QRM).unwrap(); if att.count < q { return Err(Error::QuorumNotReached); } if att.disputed { return Err(Error::Disputed); } if coherence != att.coherence { return Err(Error::CoherenceMismatch); } if execution_bh != att.execution_bh { return Err(Error::CoherenceMismatch); } if current_time > att.last_time && (current_time - att.last_time) > 300 { return Err(Error::StaleAttestation); } escrow.state = 1; escrows.set(escrow_id, escrow); env.storage().persistent().set(&KEY_ESC, &escrows); Ok(true) }
    pub fn revert_escrow(env: Env, escrow_id: BytesN<32>, _reason: u32) -> Result<bool, Error> { let mut escrows: Map<BytesN<32>, Escrow> = env.storage().persistent().get(&KEY_ESC).unwrap_or_else(|| Map::new(&env)); let mut e = match escrows.get(escrow_id.clone()) { Some(e) => e, None => return Err(Error::NotHolding) }; if e.state != 0 { return Err(Error::AlreadyReleased); } e.state = 2; escrows.set(escrow_id, e); env.storage().persistent().set(&KEY_ESC, &escrows); Ok(true) }
    pub fn get_escrow(env: Env, escrow_id: BytesN<32>) -> Option<Escrow> { let m: Map<BytesN<32>, Escrow> = env.storage().persistent().get(&KEY_ESC).unwrap_or_else(|| Map::new(&env)); m.get(escrow_id) }
    pub fn get_route_attestation(env: Env, route_id: BytesN<32>) -> Option<Attestation> { let m: Map<BytesN<32>, Attestation> = env.storage().persistent().get(&KEY_ATT).unwrap_or_else(|| Map::new(&env)); m.get(route_id) }
    pub fn is_validator(env: Env, v: Address) -> bool { let m: Map<Address, bool> = env.storage().instance().get(&KEY_VALS).unwrap_or_else(|| Map::new(&env)); m.get(v).unwrap_or(false) }
    pub fn get_quorum(env: Env) -> u32 { env.storage().instance().get(&KEY_QRM).unwrap() }
    pub fn get_validator_count(env: Env) -> u32 { env.storage().instance().get(&KEY_VCNT).unwrap_or(0) }
}
