[workspace]
resolver = "2"
members = [
    "crates/trion-common",
    "crates/trion-evm",
    "crates/trion-svm",
    "crates/trion-sui",
    "crates/trion-near",
    "crates/trion-ton",
    "crates/trion-pvm",
    "crates/trion-cosmos",
    "crates/trion-utxo",
    "crates/trion-tron",
    "crates/trion-aptos",
    "crates/trion-movement",
    "crates/trion-pi",
    "crates/trion-starknet",
    "crates/trion-botchain",
]

[workspace.dependencies]
tokio          = { version = "1", features = ["full"] }
reqwest        = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
serde          = { version = "1", features = ["derive"] }
serde_json     = "1"
sha3           = "0.10"
hex            = "0.4"
tracing        = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow         = "1"
thiserror      = "1"
async-trait    = "0.1"

[profile.release]
opt-level     = 3
lto           = "thin"
codegen-units = 1
strip         = true
