name: CI Solidity
on: [push, pull_request]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Hardhat dependencies
        working-directory: hardhat
        run: npm install --legacy-peer-deps
      - name: Compile contracts
        working-directory: hardhat
        run: npx hardhat compile
        continue-on-error: true
